congrea/virtualclass

- index.js
- src/record-play.js
- src/xhr.js
chunk num change, session create, path chage
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/22)
> Changes for recording

- ERROR_CODE.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/23)
> Error code

- css/popup.css
- css/styles.css
- example/index1.php
- export.php
- import.php
- src/popup.js
- src/progressbar.js
- src/record-play.js
improve code and fix few bug
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/24)
> improve code and fix few bug

- index.js
- src/editor.js
- src/footer-control-user.js
- src/media.js
- src/receive-messages-response.js
- src/utility.js
- src/virtualclass.js
- src/whiteboard-utility.js
- src/whiteboard.js
- src/youtube.js
Fix various bugs like, transfer/reclaim with youtube, video, text editor
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/25)
> Fix various bugs like, transfer/reclaim with youtube, video, text editor

- css/popup.css
- css/styles.css
- example/en.php
- example/index1.php
- index.js
- src/footer-control-user.js
- src/indexeddb-storage.js
- src/media.js
- src/popup.js
- src/progressbar.js
- src/record-play.js
- src/utility.js
- src/virtualclass.js
- src/whiteboard.js
- src/youtube.js
Create features like replay from start, diaoluge box, fix bugs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/30)
> Create features, fix various bugs

- css/popup.css
- css/styles.css
- example/en.php
- example/index1.php
- src/editor.js
- src/footer-control-user.js
- src/indexeddb-storage.js
- src/lang-en.js
- src/popup.js
- src/record-play.js
- src/utility.js
- src/virtualclass.js
various UI improvement and fix bugs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/32)
> various UI improvement and fix bugs

- css/popup.css
- css/styles.css
- example/auth.php
- index.js
- src/editor.js
- src/lang-en.js
- src/media.js
- src/popup.js
- src/record-play.js
- src/utility.js
- src/virtualclass.js
- src/whiteboard-utility.js
- src/youtube.js
fix various bugs and UI improvement
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/33)
> fix various bugs and UI improvement

- css/styles.css
- example/index1.php
- src/record-play.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/34)
> remove comment

- css/jquery.ui.chatbox.css
- css/popup.css
- css/styles.css
- css/vceditor.css
- example/index1.php
- index.js
- src/record-play.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/35)
> localize css and fix bugs

- css/popup.css
- example/index1.php
- src/progressbar.js
- src/xhr.js
- src/youtube.js
fix various bugs and done UI improvement
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/36)
> fix various bugs and done UI improvement

- src/record-play.js
- worker/json-chunks.js
fix bug
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/37)
> don't clear session when session is not uploaded

- src/record-play.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/38)
> make available download link

- src/record-play.js
update progress bar code
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/39)
> update code for progress bar

- src/editor.js
- src/footer-control-user.js
- src/lang-en.js
audio tool update
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/40)
> audio tool update

- css/styles.css
- src/utility.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/41)
> improve css

- css/styles.css
improve look and feel
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/42)
> improve look and feel

- src/utility.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/43)
> reduce width on editor

- css/styles.css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/44)
> disable chat list on play mode

- css/styles.css
- src/utility.js
layout fix
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/46)
> layout width fix

- example/index1.php
- src/utility.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/47)
> remove alert

- chat/chat.js
- index.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/49)
> add event parameter

- example/index1.php
- example/js.debug.php
- src/ot-server.js
- src/vceditor.js
- src/virtualclass.js
minifide js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/51)
> minifide js

- src/vceditor.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/53)
> remove amd

- src/editor-markdown.js
Remove AMD to remove conflict with moodle
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/55)
> Remove AMD to remove conflict with moodle

- chat/jquery.ui.chatbox.js
- chat/jquery.ui.chatlist.js
- chat/jquery.ui.chatroom.js
- css/popup.css
remove data section and add zindex
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/109)
> remove data section and add zindex

- chat/jquery.ui.chatbox.js
- chat/jquery.ui.chatlist.js
- chat/jquery.ui.chatroom.js
remove class
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/110)
> remove class

- css/styles.css
make correct alignment for unmuteAll
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/113)
> make correct alignment for unmuteAll

- css/styles.css
udpate css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/118)
> udpate css

- .gitignore
- Gruntfile.js
- example/index1.php
- package.json
update css path
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/155)
> update css path

- example/index1.php
change constant parameters to 0/1. For configure the settings, either 0 or 1 would be into URL.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/162)
> change constant parameters to 0/1

- bundle/jquery/css/base/black_jquery-ui.css
- bundle/jquery/css/base/gray_jquery-ui.css
- bundle/jquery/css/base/white_jquery-ui.css
fix look and feel bugs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/169)
> fix look and feel bugs

- example/index1.php
remove unuse variable
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/174)
> remove unuse variable

- example/index1.php
update config parameters
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/175)
> update config parameters

- src/indexeddb-storage.js
- src/progressbar.js
- src/record-play.js
- src/utility.js
- src/xhr.js
add 'done' pharse at data of downlable file
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/179)
> add 'done' pharse in downlable file

- bundle/io/src/iolib.js
- src/record-play.js
add more validation for download button
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/181)
> add more validation for download button

- index.js
enable editor code educator role override
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/196)
> enable editor code educator role override

- index.js
- src/virtualclass.js
Improve session clear on overriding teacher
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/199)
> Improve session clear on overriding teacher

- index.js
remove empty whiteboard from presenter
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/206)
> remove empty whiteboard from presenter

- index.js
remove role from localstorage when swith the staus of presenter
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/207)
> remove role from localstorage when swith the staus of presenter

- index.js
add validate for remove empty whiteboard message
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/208)
> add validate for remove empty whiteboard message

- src/environment-validation.js
- src/footer-control-user.js
- src/indexeddb-storage.js
- src/io-adapter.js
- src/media.js
- src/ot-text-operation.js
- src/popup.js
- src/progressbar.js
- src/receive-messages-response.js
- src/record-play.js
- src/screenshare.js
- src/utility.js
- src/virtualclass.js
- src/webrtc-adapter.js
- src/whiteboard-drawobject.js
- src/whiteboard-optimization.js
- src/whiteboard-readytextobj.js
- src/whiteboard-refresh-play.js
- src/whiteboard-utility.js
- src/whiteboard.js
- src/xhr.js
remove commented code from all javascript file.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/211)
> remove commented code

- src/youtube.js
Participate's youtube video synch when pause/play video by teacher
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vidyamantra/virtualclass/227)
> youtube video synch when pause/play video by teacher

- src/document-share.js
- src/utility.js
Fix document sharing problem on refreshing the page
> Fix document sharing problem on refreshing the page

- Gruntfile.js
- src/templates_view.js
- src/youtube.js
- templates/youtube/yts.hbs
- templates/youtube/ytscontrol.hbs
youtube html structure create using handlebar js
> youtube html structure create using handlebar js

- package.json
- src/editor.js
- src/templates_view.js
- templates/editor/edenableall.hbs
- templates/editor/editorrich.hbs
- templates/editor/messagebox.hbs
templates or handlebar and npm of editors
> templates or handlebar of editors new

- .gitignore
- Gruntfile.js
- css/modules/jquery.ui.chatbox.css
- css/modules/media.css
- css/modules/poll.css
- css/modules/styles.css
- css/theme/black.css
- css/theme/gray.css
- css/theme/white.css
- scss/theme-black.scss
- scss/theme-gray.scss
- src/templates_view.js
- src/virtualclass.js
> all background changes from js and css

- Gruntfile.js
- package.json
- src/templates_view.js
- src/utility.js
- src/virtualclass.js
- templates/dashboard.hbs
- templates/dashboardCont.hbs
- templates/dashboardNav.hbs
- templates/main.hbs
merge and add base for dashboard
> merge and add base for dashboard

- src/templates_view.js
- src/virtualclass.js
- templates/recordingControl.hbs
> solution of replay

- css/modules/document-share.css
- css/modules/whiteboard.css
- src/document-share.js
- src/whiteboard-canvas-utility.js
- src/whiteboard-drawobject.js
- src/whiteboard-refresh-play.js
- src/whiteboard.js
> make whiteboard at center

- fileuploader/js/fine-uploader.js
- src/congrea-uploader.js
- src/page.js
- src/templates_view.js
- src/upload-video.js
- src/utility.js
- templates/dashboard.hbs
- templates/documentSharing/dashboard.hbs
- templates/documentSharing/docsMain.hbs
handle drag and drop issue for dashboard
> handle drag and drop issue for dashboard

- chat/chat.js
- chat/jquery.ui.chatlist.js
- chat/jquery.ui.chatroom.js
- chat/lib.js
- css/modules/styles.css
- index.js
- src/footer-control-user.js
- src/io-missing-packets.js
- src/io-ping-pong.js
- src/lang-en.js
- src/media.js
- src/poll.js
- src/precheck.js
- src/screenshare.js
- src/templates_view.js
- src/utility.js
- src/view.js
- src/webrtc-adapter.js
- templates/chat/chatuser.hbs
- worker/screendecode.js
- worker/screenworker.js
Improve Audio, Chat use list, CPU utilisation and more
> Improve Audio, Chat use list, CPU utilisation and more

- css/modules/dashboard.css
- src/media.js
- src/utility.js
- src/virtualclass.js
Trigger dashboard if video, docs, and presentation list is empty
> Trigger dashboard if video, docs, and presentation list is empty

- css/modules/dashboard.css
- css/modules/dbPpt.css
- css/modules/dbVideo.css
- css/modules/document-share.css
- css/modules/styles.css
- src/document-share.js
- src/lang-en.js
- src/page.js
- src/templates_view.js
- src/utility.js
- src/virtualclass.js
- templates/chat/stickycont.hbs
- templates/documentSharing/dashboard.hbs
Fix document-sharing bugs and improve UI
> Fix document-sharing bugs and improve UI

- css/modules/document-share.css
- css/modules/styles.css
- css/modules/video.css
- css/modules/youtube.css
- src/lang-en.js
- src/video-host.js
- src/view.js
> Improve UI

- css/modules/dbPpt.css
- css/modules/dbVideo.css
- css/modules/poll.css
- css/modules/styles.css
- css/modules/youtube.css
- css/white/jquery.ui.chatbox.css
- css/white/styles.css
> change design upload video and ppt share

- css/modules/dashboard.css
- css/modules/dbPpt.css
- css/modules/styles.css
- src/pptshare.js
- src/utility.js
Fix file upload bug and improve UI
> Fix file upload bug and improve UI

- index.js
- src/media.js
Suppress click sound and Dynamic speed algo
> Suppress click sound and Dynamic speed algo

- css/modules/sharepresentation.css
- css/modules/styles.css
- css/modules/video.css
- css/modules/youtube.css
- src/templates_view.js
- templates/ppt/pptiframe.hbs
> Improve User Interface

- css/modules/dashboard.css
- css/modules/styles.css
- src/lang-en.js
- src/poll.js
- src/quiz.js
- src/templates_view.js
- src/utility.js
- templates/dashboardNav.hbs
strings converts by language file
> strings converts by language file

- css/modules/dashboard.css
- css/modules/dbPpt.css
- css/modules/dbVideo.css
- css/modules/document-share.css
- css/modules/icon.css
- css/modules/styles.css
- src/document-share.js
- src/virtualclass.js
Improve Dashboard Pop for documents, video and presentation sharing
> Improve Dashboard Pop for documents, video and presentation sharing

- src/footer-control-user.js
- src/media.js
- src/utility.js
Enable audio on webcam's unavailibility
--
> 	Enable audio on webcam's unavailibility

- css/modules/styles.css
- src/document-share.js
- src/utility.js
- src/video-host.js
Fix bugs like alert-null, poll-dialogue box and improve css
> Fix bugs like alert-null, poll-dialogue box and improve css

- css/modules/icon.css
- css/modules/styles.css
- src/lang-en.js
- src/popup.js
- src/screenshare-getscreen.js
- src/screenshare.js
- src/templates_view.js
- src/video-host.js
- templates/popupCont.hbs
Fix desktop selector(chrome plugin) message
> Fix desktop selector(chrome plugin) message

- css/modules/dashboard.css
- css/modules/icon.css
- src/dashboard.js
- src/pptshare.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
Handle 'Dashboard Navigation' robustly
> Handle 'Dashboard Navigation' robustly 

- example/index1.php
- v.vidya.io/index.php
index.php update for v.vidya.io
> index.php update for v.vidya.io

- example/js.debug.php
- v.vidya.io/index.php
update resources file for v.vidya.io
> update resources file for v.vidya.io

- v.vidya.io/index.php
> fix syntax error at index.php

- v.vidya.io/index.php
> change authentication code

- v.vidya.io/index.php
fix various bus for v.vidya.io
> fix various bus for v.vidya.io

- src/indexeddb-storage.js
make inactive audio on new session
> make inactive audio on new session

- css/modules/styles.css
- src/environment-validation.js
- src/templates_view.js
- templates/whiteboard/main.hbs
A4 sample pdf size and fix minor bugs
> A4 sample pdf size and fix minor bugs

- src/xhrn.js
> Get access

- css/modules/dashboard.css
- css/modules/document-share.css
- css/modules/styles.css
- css/modules/video.css
- css/modules/whiteboard.css
Fix bugs and improve look/feel
> Fix bugs and improve look/feel

- build/js.debug.php
- bundle/io/src/iolib.js
- example/js.debug.php
- index.js
- src/document-share.js
- src/server-data.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
> Handle doc order

- src/document-share.js
- src/server-data.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
Error handling for send/retrieve orders
> Error handling for send/retrieve orders

- css/modules/dbVideo.css
- css/modules/styles.css
- s3/s3.fine-uploader.js
- src/congrea-uploader.js
- src/document-share.js
- src/indexeddb-storage.js
- src/server-data.js
- src/upload-video.js
- src/utility.js
Retain status on document sharing
> Retain status on document sharing

- src/document-share.js
- src/page.js
Isolate drag and drop for Document and Video sharing
> Isolate drag and drop for Document and Video sharing

- css/modules/multivideo.css
- css/modules/styles.css
- example/auth.php
- src/congrea-uploader.js
- src/media.js
- src/templates_view.js
- src/utility.js
- templates/chat/chatuser.hbs
Improve resource on peer-to-peer video
> Improve resource on peer-to-peer video

- src/pptshare.js
- src/upload-video.js
- src/utility.js
Fix re-arrange for Ppt Sharing
> Fix re-arrange for Ppt Sharing

- css/modules/document-share.css
- css/modules/styles.css
- src/congrea-uploader.js
- src/page.js
- src/templates_view.js
- src/upload-video.js
- src/utility.js
- templates/videoupload/popup.hbs
> Improve UI and fix bugs

- src/screenshare.js
Handle https with chrome extension
> Handle https with chrome extension

- chat/chat.js
- example/index1.php
Add resource files for stand-alone version
> Add resource files for stand-alone version

- css/modules/dashboard.css
- css/modules/dbPpt.css
- css/modules/dbVideo.css
- css/modules/document-share.css
- css/modules/icon.css
- css/modules/poll.css
- css/modules/styles.css
- src/templates_view.js
- src/utility.js
- templates/documentSharing/docsNav.hbs
- templates/videoupload/popup.hbs
> document sharing UI

- css/modules/dashboard.css
- css/modules/document-share.css
- css/modules/jquery.ui.chatbox.css
- css/modules/media.css
- css/modules/multivideo.css
- css/modules/popup.css
- css/modules/progress.css
- css/modules/styles.css
> improve virtualclass Ui

- css/modules/dbVideo.css
- css/modules/jquery.ui.chatbox.css
- css/modules/poll.css
- css/modules/styles.css
- src/templates_view.js
- templates/chat/stickycont.hbs
> updated virtualclass UI

- css/modules/dbVideo.css
- src/upload-video.js
- src/utility.js
> code modified to update video poster and reload handled

- css/modules/styles.css
> poll and quiz popups

- chat/chat.js
- css/modules/styles.css
- src/congrea-uploader.js
- src/server-data.js
- src/utility.js
- src/xhr.js
- src/xhrn.js
> make key dynamic

- css/modules/dbPpt.css
- css/modules/dbVideo.css
- css/modules/styles.css
video contrls and ppt cntrls align
> video contrls and ppt cntrls align 

- src/server-data.js
- src/upload-video.js
> Add validations

- css/modules/styles.css
> docshare cntrls

- css/modules/poll.css
- css/modules/quiz.css
- css/modules/sharepresentation.css
- css/modules/video.css
- css/modules/youtube.css
- example/auth.php
- example/index1.php
- src/utility.js
> Set main layout dimension

- chat/chat.js
- src/pptshare.js
- src/server-data.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
- src/xhrn.js
Handle dimension, orders and duplicate dimension
> Handle dimension, orders and duplicate dimension

- css/modules/styles.css
> chat bkground

- src/congrea-uploader.js
- src/pptshare.js
- src/upload-video.js
Add validation for file size and remove unused code
> Add validation for file size and remove unused code

- css/modules/styles.css
- src/record-play.js
> Enable UI for record and play

- css/modules/editor.css
- css/modules/popup.css
- css/modules/styles.css
enable editor btn and progress bar
> enable editor btn and progress bar

- css/modules/dashboard.css
- css/modules/dbVideo.css
- css/modules/document-share.css
- css/modules/editor.css
- css/modules/styles.css
- css/modules/video.css
> improve ui 

- codemirror/mode/xml/index.html
- codemirror/mode/xml/test.js
- codemirror/mode/xml/xml.js
- css/modules/dashboard.css
- css/modules/document-share.css
- src/congrea-uploader.js
- src/environment-validation.js
- src/zoom.js
Fix bug like black screen, app dimension
> Fix bug like black screen, app dimension

- example/auth.php
- src/congrea-uploader.js
- src/document-share.js
- src/utility.js
Handle alert null in document-haring on page refresh
> Handle alert null in document-haring on page refresh

- example/auth.php
- example/index1.php
- src/congrea-uploader.js
- src/document-share.js
- src/indexeddb-storage.js
- src/pdf-render.js
- src/server-data.js
- src/utility.js
- src/virtualclass.js
- src/whiteboard-readytextobj.js
- src/whiteboard-utility.js
- src/xhrn.js
Make room dynamic and fix other bugs
> Make room dynamic and fix other bugs

- css/modules/dashboard.css
- css/modules/dbVideo.css
- example/auth.php
- example/index1.php
- src/document-share.js
- src/virtualclass.js
> Fix bugs and improve UI

- src/pptshare.js
- src/upload-video.js
Add validation on ppts/videos orders
> Add validation on ppts/videos orders

- src/document-share.js
- src/indexeddb-storage.js
- src/virtualclass.js
Handles alert null of element after session expire
> Handles alert null of element after session expire

- css/modules/dashboard.css
- css/modules/dbVideo.css
- css/modules/document-share.css
- css/modules/styles.css
- css/modules/vceditor.css
> Improve css on html5 doctype

- css/modules/styles.css
- src/environment-validation.js
Handle height for docs and whiteboard
> Handle height for docs and whiteboard

- css/modules/document-share.css
- src/environment-validation.js
- src/utility.js
> Update layout dimension

- css/modules/dashboard.css
- css/modules/document-share.css
- src/document-share.js
- src/utility.js
Prevent multiple up-loader on document sharing
> Prevent multiple up-loader on document sharing

- css/modules/dashboard.css
- css/modules/dbPpt.css
- css/modules/editor.css
- css/modules/jquery.ui.chatbox.css
- css/modules/media.css
- css/modules/poll.css
- css/modules/styles.css
- css/modules/vceditor.css
improve ui right bar,dashboard
> improve ui right bar,dashboard

- src/document-share.js
- src/utility.js
- src/virtualclass.js
- src/whiteboard-common.js
Delay 300 milliseconds on whiteboard navigation
>  Delay whiteboard navigation

- css/modules/document-share.css
- src/document-share.js
- src/pdf-render.js
- src/templates_view.js
- src/virtualclass.js
- templates/videoupload/popup.hbs
Enable navigation on pdf rendered and fix bugs
> Enable navigation on pdf rendered and fix bugs

- src/environment-validation.js
- src/utility.js
- src/whiteboard-readytextobj.js
- src/whiteboard-utility.js
> Fix bugs on whiteboards

- chat/lib.js
- css/modules/document-share.css
- templates/chat/chatCont.hbs
- templates/chat/chatMain.hbs
> Fix common-chat layout

- css/modules/dashboard.css
- css/modules/dbVideo.css
- css/modules/document-share.css
- css/modules/jquery.ui.chatbox.css
- css/modules/popup.css
- css/modules/styles.css
- css/modules/vceditor.css
- css/modules/video.css
- src/environment-validation.js
- src/popup.js
- src/templates_view.js
- src/utility.js
- templates/videoupload/videoupload.hbs
> Fix bugs related to UI

- build/js.debug.php
- src/api.js
- src/congrea-uploader.js
- src/document-share.js
- src/page.js
- src/pptshare.js
- src/server-data.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
- src/xhrn.js
Add api files and work on layout
> Add api files and work on layout

- bundle/io/src/iolib.js
- src/api.js
- src/utility.js
- src/video-host.js
Ping only when on web-socket is connected
> Ping only when on web-socket is connected

- bundle/io/src/iolib.js
- example/js.debug.php
- index.js
- src/media.js
- src/pptshare.js
Handle user-list with new property and prevent live-image on web-socket disconnection
> Handle user-list with new property and prevent live-image on web-socket disconnection

- css/modules/dbVideo.css
- css/modules/poll.css
- css/modules/styles.css
> poll popup

- src/document-share.js
- src/lang-en.js
- src/utility.js
Update deleted docs on local storage
Handle dashboard on toggling Video and Document
> Handle dashboard with navigation and update deleted docs on local storage

- src/ot-editor-client.js
Restrict frequent cursor selection
> Restrict frequent cursor selection

- bundle/io/src/iolib.js
- css/modules/styles.css
- index.js
- src/lang-en.js
- src/utility.js
- src/view.js
- src/whiteboard-utility.js
> Handle message gracefully

- bundle/io/src/iolib.js
- index.js
- src/utility.js
Stop connection on multiple and invalid login
> Stop connection on multiple and invalid login

- index.js
- src/io-adapter.js
- src/io-ping-pong.js
Delay packets of pong and tConn
> Delay packets of pong and tConn

- bundle/io/src/iolib.js
- index.js
- src/utility.js
- src/whiteboard-common.js
Handle user list on joining of new user
> Handle user list on joining of new user

- src/lang-en.js
- src/media.js
- src/video-ajax.js
- src/video-host.js
- src/video-script.js
- worker/webptopng.js
Send small videos with webp and use png as webp fallback
> Send small videos with webp and use png as webp fallback

- src/document-share.js
- src/indexeddb-storage.js
- src/page.js
Improve performance on selecting doc with lot of notes
> Improve performance on selecting doc with lot of notes

- src/document-share.js
- src/environment-validation.js
- src/pdf-render.js
- src/precheck.js
- src/utility.js
- src/video-host.js
- src/view.js
- src/webrtc-adapter.js
- src/whiteboard-common.js
Fix dimension issues in whiteboard resizing
> Fix dimension issues in whiteboard resizing

- src/document-share.js
- src/pdf-render.js
- src/view.js
- src/virtualclass.js
- src/zoom.js
Remove black screen on joining of new user, resizing window, and clicking on zoom controller
> Remove black screen on joining of new user, resizing window, and clicking on zoom controller

- css/modules/document-share.css
- src/templates_view.js
- templates/documentSharing/screen.hbs
Display loader on pdf loading with document sharing
> Display loader on pdf loading

- css/modules/jquery.ui.chatbox.css
- css/modules/styles.css
> chat block icon fixed

- index.js
- src/editor.js
- src/indexeddb-storage.js
- src/screenshare.js
- src/utility.js
Handle student-screen-sharing on page refresh and new user joining
> Handle student-screen-sharing on page refresh and new user joining

- css/modules/styles.css
- index.js
- src/footer-control-user.js
- src/screenshare.js
- src/utility.js
Add sign of which student is screen sharing
>  Add sign of which student is screen sharing

- css/modules/jquery.ui.chatbox.css
- css/modules/screenshare.css
- css/modules/styles.css
- src/screenshare.js
- src/templates_view.js
- templates/ssmainDiv.hbs
> student screen share fixed

- index.js
- src/footer-control-user.js
- src/indexeddb-storage.js
- src/screenshare.js
- src/utility.js
Fix highlighting issue on simultaneous(teacher/student) refresh
> Fix highlighting issue on simultaneous(teacher/student) refresh

- css/modules/screenshare.css
- css/modules/styles.css
- src/templates_view.js
- templates/chat/chatuser.hbs
> improve ssbtns

- css/modules/jquery.ui.chatbox.css
- css/modules/styles.css
- src/templates_view.js
- templates/chat/chatuser.hbs
> improve conrollers ui

- example/js.debug.php
- src/raise-hand.js
> Add resources

- src/environment-validation.js
- src/utility.js
- src/virtualclass.js
- src/zoom.js
> Fix bugs about dimension

- css/modules/styles.css
- src/environment-validation.js
- src/utility.js
- src/view.js
- src/zoom.js
> Improve layout view on resize

- index.js
- src/environment-validation.js
- src/utility.js
- src/view.js
- src/virtualclass.js
Fix whiteboard dimension issue updating current whiteboard
> Fix whiteboard dimension issue updating current whiteboard

- index.js
- src/document-share.js
- src/utility.js
Resize window on current whiteboard slide if required
> Resize window on current whiteboard slide if required

- css/modules/poll.css
- css/modules/screenshare.css
- css/modules/styles.css
- src/lang-en.js
improve screen share ui and strings
> improve screen share ui and strings

- css/modules/screenshare.css
- css/modules/styles.css
- css/modules/whiteboard.css
- src/pdf-render.js
Fix few layout issue about Microsoft edge
>  Fix few layout issue about Microsoft edge

- example/index1.php
- src/screenshare.js
- src/utility.js
- src/virtualclass.js
- src/zoom.js
Fixes few bugs, like, text wrapper on page refresh
> Fixes few bugs

- src/document-share.js
- src/editor.js
- src/multi-video.js
- src/poll.js
- src/pptshare.js
- src/quiz.js
- src/screenshare.js
- src/templates_view.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
- src/youtube.js
- templates/appTools.hbs
- templates/leftBar.hbs
Change the structure of main app container
> Change the structure of main app container

- css/modules/dashboard.css
- css/modules/document-share.css
- css/modules/editor.css
- css/modules/main-container-layout.css
- css/modules/poll.css
- css/modules/quiz.css
- css/modules/screenshare.css
- css/modules/sharepresentation.css
- css/modules/styles.css
- css/modules/vceditor.css
- css/modules/video.css
- css/modules/whiteboard.css
- css/modules/youtube.css
- example/index1.php
- example/js.debug.php
- index.js
- src/environment-validation.js
- src/io-adapter.js
- src/media.js
- src/network.js
- src/pdf-render.js
- src/templates_view.js
- src/utility.js
- src/video-host.js
- src/virtualclass.js
- src/whiteboard-common.js
- src/whiteboard-drawobject.js
- src/whiteboard.js
- src/zoom.js
- templates/leftBar.hbs
Improvement on layout, algorithm of audio an video and fixes other bugs
> Improvement on layout, algorithm of audio an video and fixes other bugs

- src/pdf-render.js
Increase the canvas width on fit to screen
> Increase the canvas width on fit to screen

- example/auth.php
- example/js.debug.php
- src/media.js
- src/virtualclass.js
- worker/audio-processor.js
- worker/receiver-audio-processor.js
Implement Audio worklet with fallback
> Implement Audio worklet with fallback

- src/media.js
- worker/receiver-audio-processor.js
> Improve audio worklet

- src/media.js
> Remove extra audioSend

- css/modules/editor.css
- src/utility.js
- src/virtualclass.js
Hide code editor and allow to upload single document or video
> Hide code editor and allow to upload single document or video

- index.js
- src/document-share.js
- src/pdf-render.js
- src/server-data.js
- src/video-host.js
Handle exception for uploaded files and fix bug
>  Handle exception for uploaded files and fix bug

- css/modules/network.css
- css/modules/right-sidebar.css
- index.js
- src/video-host.js
Retain teacher video status on student side
>  Retain teacher video status on student side

- chat/chat.js
- chat/lib.js
- css/modules/jquery.ui.chatbox.css
- index.js
- src/footer-control-user.js
>  Disable chat on page refresh

- css/modules/styles.css
- index.js
- src/footer-control-user.js
- src/media.js
- src/utility.js
>  Disable common chat and audio

- css/modules/styles.css
- src/environment-validation.js
- src/pdf-render.js
Disable whiteboard and document navigation on resize
> Disable whiteboard and document navigation on resize

- src/media.js
Remove audio control from local storage
> Remove audio control from local storage

- css/modules/right-sidebar.css
- css/modules/styles.css
- css/modules/video.css
> Update Right Side Bar.

- src/document-share.js
Fix bug on page refresh at student while unselected all document
> Fix bug on page refresh at student while unselected all document

- src/indexeddb-storage.js
- src/screenshare.js
- src/utility.js
- src/zoom.js
Reset audio setting after clear session and resolve zoom controller conflict
>  Reset audio setting after clear session and resolve zoom controller conflict

- src/media.js
> Rename classname for webcam

- css/modules/styles.css
- example/index1.php
Hide Poll and Quiz if congrea is not served from cms/lms
> Hide Poll and Quiz if congrea is not served from cms/lms

- src/pdf-render.js
- src/zoom.js
Use virtualclass container for whiteboard offset
>  Use virtualclass container for whiteboard offset

- index.js
- src/indexeddb-storage.js
- src/utility.js
- src/virtualclass.js
Make whiteboard is default app in every condition
> Make whiteboard is default app in every condition

- css/modules/main-container-layout.css
- css/modules/quiz.css
- css/modules/sharepresentation.css
- css/modules/vceditor.css
Remove space from student layout
> Remove space from student layout

- css/modules/popup.css
- src/editor.js
- src/lang-en.js
- src/templates_view.js
- templates/editor/edenableall.hbs
editor collaboration allow or not allow
> editor collaboration allow or not allow

- css/modules/document-share.css
- src/record-play.js
> Fix few issues

- css/modules/styles.css
- src/color-selector.js
> Remove extra border

- src/document-share.js
Add prefix docs and add delay on document sharing
> Add prefix docs and add delay on document sharing

- bundle/io/src/iolib.js
- src/indexeddb-storage.js
- src/pdf-render.js
- src/whiteboard-canvas-utility.js
- src/whiteboard-drawobject.js
- src/whiteboard-packet-queue.js
- src/whiteboard-utility.js
- src/whiteboard.js
Fix free drawing problem for new user
> Fix freedrawing problem for new user

- index.js
- src/document-share.js
- src/indexeddb-storage.js
- src/pdf-render.js
- src/utility.js
- src/whiteboard-utility.js
Hide document will shared shortly
> Hide document will shared shortly

- src/whiteboard-utility.js
restore replayObjsByFilter function
> restore replayObjsByFilter function

- src/media.js
> Fix audio student problem

- worker/receiver-audio-processor.js
> Convert let to var

- worker/receiver-audio-processor.js
> Experiment audio

- src/video-host.js
> Display video on re-play

- css/modules/styles.css
- src/lang-en.js
- src/record-play.js
Error handling on recording session
> Error handling on recording session

- Gruntfile.js
- example/index1.php
> Restructure files and folder

- css/modules/quiz.css
> remove fixed scroll

- example/auth.php
> Revert back auth.php file

- css/modules/styles.css
> Fix video-submit-button

- example/auth.php
> Dynamic role in auth.php

- index.js
Increase waiting time to send screen for new user
> Increase waiting time to send screen for new user

- css/modules/jquery.ui.chatbox.css
- css/modules/poll.css
- src/chat.js
- src/utility.js
- src/view.js
chat list height UI problem fixed
> chat list height UI problem fixed

- src/iolib.js
- src/pdf-render.js
- src/upload-video.js
- src/utility.js
Play binary data on recording and play
>  Play binary data on recording and play

- src/multi-video.js
- src/templates_view.js
- templates/audioWidget.hbs
Add total users on meeting mode
> Add total users on meeting mode

- example/index1.php
> update index file

- css/modules/whiteboard.css
Temporary hide whiteboard navigation
> Temporary hide whiteboard navigation

- css/modules/document-share.css
- css/modules/multivideo.css
- example/auth.php
- index.js
- src/chat-lib.js
- src/indexeddb-storage.js
- src/page-navigation.js
- src/virtualclass.js
- src/whiteboard-common.js
Fix bug related to navigation of document and whiteboard
> Fix various bugs related to navigation of whiteboard

- example/auth.php
- index.js
Remove temporary fix when user removing
> Remove temporary fix when user removing

- Gruntfile.js
Exclude css minify from main task in grunt
> Exclude css minify from main task in grunt

- src/media.js
- src/pdf-render.js
- src/virtualclass.js
- src/zoom.js
Set to fitToScreen for first document
> Set to fitToScreen for first document

- src/environment-validation.js
- src/pdf-render.js
- src/virtualclass.js
Fit to screen for document sharing and whiteboard
> Fit to screen for document sharing and whiteboard

- example/index1.php
- src/whiteboard-freedrawing.js
> Make thin free drawing stroke

- index.js
Disconnect web socket on student when session ending
> Disconnect web socket on student when session ending

- src/document-share.js
> Fix spelling error

- src/dashboard.js
- src/document-share.js
- src/index.js
- src/pptshare.js
- src/upload-video.js
- src/utility.js
- src/virtualclass.js
Fix and order (documentshare/video/presentation)
> Fix and order (documentshare/video/presentation)

- src/live-stream.js
> Delete first file for ogv

- src/live-stream.js
> Changes for ogv

- src/live-stream.js
Stop ogv audio play back on app switch
> Stop ogv audio play back on app switch

- src/live-stream.js
> Create different ogv instance

- src/live-stream.js
Create single ogv instance only
> Create single ogv instance only

- src/live-stream.js
> Ogv changes

- src/live-stream.js
> Add logging for ogv video

- src/live-stream.js
> Off logging for ogv

- src/live-stream.js
> Disable webgl for ogv video

- src/live-stream.js
> Enable webgl for ogv

- lang/lang-en.js
- lang/lang-es.js
- lang/lang-pt_br.js
- src/live-stream.js
- src/popup.js
> Change user gesture button

- src/live-stream.js
> Add logging

- build/ogv/ogv-demuxer-webm-wasm.js
> Disable console

- src/popup.js
Avoid multiple handlers for ogv video gesture element
> Avoid multiple handlers for ogv video gesture element
